config/routes.rb
Rails.application.routes.draw do

  resources 'events'
  resources :users
  resources 'games'
  get 'events/:id/bracket' => 'events#show_bracket', as: :bracket
  get 'events/:id/new_round' => 'events#new_round', as: :new_round
  patch 'events/:id/bracket' =>  'events#update_bracket', as: :update_bracket
  delete 'events/:id/undo_round' => 'events#undo_round', as: :undo_round
  patch 'events/:id/save_event' => 'events#save_event', as: :save_event
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new',  via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get', via: 'delete'

  get 'template/index', :path => 'template'
  get 'template/new'
  get 'template/show'
  get 'template/edit'

  get 'mockup/index', :path => 'mockup-login'
  get 'mockup/new', :path => 'mockup-new-event'
  get 'mockup/events', :path => 'mockup-events'
  get 'mockup/info', :path => 'mockup-event-info'
  get 'mockup/checkin', :path => 'mockup-event-checkin'
  get 'mockup/brackets', :path => 'mockup-event-brackets'
  get 'mockup/summary', :path => 'mockup-event-summary'

  root 'sessions#new'#'mockup#index' 

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :rounds
  accepts_nested_attributes_for :rounds, :update_only => true
  serialize :teams, Array 
  serialize :scores, Hash 

  #THE FOLLOWING IS FOR 1v1 NON-ELIM ONLY
  # This is super hacky because it was originally
  # set up for 2 team matches.
  #
  # The round number is used for bye information,
  # while the teams hash is a pair table to
  # ensure that matchups don't happen more than
  # once.
  #
  # Also, the score hash depends on the hash order
  # to retrieve players, as well as holding scores.
  #
  # Once setup_match() has been called, adding
  # additional players to the event will have
  # no effect on the matchup/scores.
  #
  # TODO: Find better methods for generating
  # pairs and storing data.

  def setup_match
    # there must be at least two players.
    # TODO: this needs an assert statement.

    players = users.select { |u| u.type = 'Player' }
    players.shuffle!

    self.scores = Hash.new
    # use score hash to hold players
    players.each do |p|
      self.scores[p] = [0,0,0] #Losses, Wins, Ties
    end
  end

  def generate_round
    if rounds.empty?
      setup_match
    end

    # advance round num
    r_num = rounds.empty? ? 1 : rounds.last.round_number + 1

    curr_round = Round.new(round_number: r_num, active: true)

    # order players from lowest to highest score 
    self.scores = Hash[self.scores.sort_by { |p, s| s[1] }]
    players = Array.new
    self.scores.each do |p,s|
      players << p
    end

    # if bye is present
    # account for bye 
    if players.count % 2 != 0
      spectator = find_bye 
      curr_round.byes = { 0 => spectator }
      players.delete spectator 
    end

    #set previous round as history
    if rounds.last
      rounds.last.active = false
      rounds.last.save!
    end

    # create matchups
    # TODO: account for byes
    matchups = Array.new
    i = 0
    for i in 0..(players.count/2-1) do
      matchups << [players[2*i], players[2*i+1]] 
    end

    # make games 
    matchups.each do |p1,p2|
      new_game = make_and_return_game(p1,p2)
      curr_round.games << new_game
      curr_round.save!
    end
    rounds << curr_round
    save!
  end

  def make_and_return_game(player_1,player_2)
      game = Game.new #winner is set later
      game.contestants << player_1
      game.contestants << player_2 
      game.save!
      return game
  end

  # score format is [L,W,T]
  def calculate_scores
    self.scores.each do |k,v|
      self.scores[k] = [0,0,0]
    end
    rounds.each do |r|
      r.games.order("id")
      r.games.each do |g|
	p1 = g.contestants[0]
	p2 = g.contestants[1]
	if g.tie?
	  self.scores[p1][2] += 1
	  self.scores[p2][2] += 1
	  # may as well update the tie while we're here
	  g.p1_win = false
	  g.p2_win = false
	  g.save!
	elsif g.p1_win?
	  self.scores[p1][1] += 1
	  self.scores[p2][0] += 1
	else
	  self.scores[p1][0] += 1
	  self.scores[p2][1] += 1
	end
      end 
      save!
   end
  end

  def get_bottom_players
    sorted = Hash[self.scores.sort_by { |p, s| s[1] }]
    players = Array.new
    if sorted.empty?
      return Array.empty
    end
    wins = sorted[sorted.keys.first][1]
    sorted.each do |k,v|
      if v[1] == wins   
	players << k
	next
      end
      break
    end
    return players
  end

  # should be called BEFORE starting a new round!
  def find_bye
    if rounds.empty?
      #return a random player
      return users.select { |u| u.type="Player" }.sample
    else
      bottom_players = get_bottom_players
      rounds.reverse_each do |r|
	# TODO: there should be a clearer way to store/access this
	player = r.byes[0]
	if bottom_players.include? player
	  if bottom_players.count == 1
	    break
	  end
	  bottom_players.delete player 
	end
      end
      # loop may not have completely reduced results,
      # but in either case we can sample from them
      return bottom_players.sample
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  helper_method :shorten_str, :num_players
  def index
    @events = Event.all
  end

  def create
    @event = Event.new event_params
    if @event.save
      flash[:success] = 'Successfully created event!'
      redirect_to events_path
    else
      render 'new'
    end
    
  end

  def show
    @event = Event.find params[:id]
  end

  def show_bracket
    @event = Event.find params[:id]
    @new_round = @event.rounds.last
    @new_round_disabled = num_players(@event) < 2
    render 'show-bracket'
  end

  def create_round
    @event = Event.find params [:id]
  end

  def edit
    @event = Event.find params[:id]
  end

  def new
    @event = Event.new
  end

  def update
    @event = Event.find params[:id]
    if @event.update_attributes event_params
      flash[:success] = 'Event successfully updated!'
      redirect_to @event
    else
      render 'show'
    end
  end

  def save_event
    @event = Event.find params[:id]
    if @event.update_attributes event_params
      @event.calculate_scores
      redirect_to :action => :show_bracket
    else
      render 'show' #for error checks
    end
  end

  def update_bracket
    @event = Event.find params[:id]
    # last round can't be active!
    if @event.rounds.last == nil or !@event.rounds.last.active
      @event.generate_round
      @rounds = @event.rounds
      @event.save!
      @new_round = @event.rounds.last
      render 'show-bracket'
    else
      if @event.update_attributes event_params
        flash[:success] = 'Event successfully updated!'
        @event.calculate_scores
        render 'show-bracket'
      else
        render 'show'
      end
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to events_path 
  end

  def undo_round
    @event = Event.find(params[:id])
    if !@event.rounds.empty?
      @event.rounds.last.destroy
      render 'show-bracket'
    end
  end
  
  def shorten_str(str,len)
    str.length > len ? str[0..len] + '...' : str[0..-1] 
  end

  def num_players(event)
    p = event.users.select { |u| u.type = 'Player' }
    return p.count
  end

private

def event_params
  params.require(:event).permit(:id, :name, :date, :bracket, :event_type, :description, rounds_attributes: [:id, :round_number, :active, :byes, games_attributes: [:id, :p1_win, :p2_win]])
end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1 class="notification">Edit <span class="orange"><%=@event.name%></span></h1>
<%= form_for @event do |f| %>
<div class="form">
  <table>
    <tr>
      <th>Type</th>
      <th>Value</th>
    </tr>
    <tr>
      <td style="width: 150px;">Name</td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td style="width: 150px;">Date</td>
      <td><%= f.text_field :date %></td>
    </tr>
    <tr>
      <td style="width: 150px;">Type</td>
      <td>
        <%=f.select :event_type, options_for_select(['Netrunner','Magic The Gathering','Pokemon'])%>
      </td>
    </tr>
    <tr>
      <td style="width: 150px;">Bracket</td>
      <td>
        <%=f.select :bracket, options_for_select(%w[Non-Elimination])%>
      </td>
    </tr>
    <tr style="height: 150px;">
      <td style="width: 150px;">Description</td>
      <td><%=f.text_area :description%></td>
    </tr>
  </table>
<%= f.submit 'Update Event', :class => "submit"%>
<% end%>
<div style="white-space:nowrap;">
  <a href=<%=event_path(@event)%> data-confirm="Are you sure you want to delete this event?" data-method="delete"><button class="submit" style="background: #db4435; margin-left: 15px;">Delete</button></a>
  <a href=<%=event_path(@event)%>><button class="submit" style="background: #b3b3b3; margin-left: 15px;">Cancel</button></a>
  </div>
</div>

app/views/events/index.html.erb
<% if flash[:success] %>
  <div class="action-notification">
    <img src="/assets/notification.svg">
    <span><%= flash[:success] %></span>
  </div>
  <div class="action-notification-spacer"></div>
<% end %>
<h1 class="notification"> Your <span class="orange"> Upcoming Events </span> </h1>
<% @events.each do |event| %>
<div class="event">
  <img src="<%= image_path('netrunner.jpg') %>"/>
  <h1> <%= shorten_str(event.name,18) %> </h1>
  <p> <%= event.type %> </p>
  <p class="description"> <%= shorten_str(event.description,70) %> </p>
  <img class="date" src="<%= image_path('date.svg') %>"/><span> <%= event.date %> </span>
  <%= link_to "Manage", event_path(event) %>
</div>
<% end %>

app/views/events/new.html.erb
<h1 class="notification"> Create A <span class="orange"> New Event </span></h1>
<%= form_for @event do |f| %>
<div class="form">
  <table>
    <tr>
      <th>Type</th>
      <th>Value</th>
    </tr>
    <tr>
      <td style="width: 150px;">Name</td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td style="width: 150px;">Date</td>
      <td><%= f.text_field :date %></td>
    </tr>
    <tr>
      <td style="width: 150px;">Type</td>
      <td>
        <%=f.select :event_type, options_for_select(['Netrunner','Magic The Gathering','Pokemon'])%>
      </td>
    </tr>
    <tr>
      <td style="width: 150px;">Bracket</td>
      <td>
        <%=f.select :bracket, options_for_select(%w[Non-Elimination])%>
      </td>
    </tr>
    <tr style="height: 150px">
      <td style="width: 150px;">Description</td>
      <td><%=f.text_area :description%></td>
    </tr>
  </table>
<%= f.submit 'Create Event', :class => "submit"%>
<% end %>
  <a href=<%= events_path%>><button style="background: #b3b3b3; margin-left: 15px;">Cancel</button></a>
</div>

app/views/events/show-bracket.html.erb
<script>
$(function() {
  $( "#dialog" ).dialog({
    autoOpen: false,
  });

  $( ".result" ).click(function() {
    $('#event_form').submit();
  });

  $( ".checkbox input" ).click(function() {
    document.eform.action ="<%= url_for(:controller => 'events', :action => 'save_event') %>"
    eform.submit();
  });
});

</script>
<div id="dialog" title="Match Result">
  <p>Who won the match?</p>
  <button class="left-button"> Player 1 </button>
  <button class="center-button"> Player 2 </button>
  <button class="right-button"> Tie </button>
</div>

<%= form_for @event, url: { :action => :update_bracket }, 
  :html => {:id => 'event_form', :name => 'eform' }  do |f| %>
<h1 class="notification"><%=@event.name%><span class="orange"> Brackets </span></h1>

<div class="event-management">
  <% if @new_round_disabled %>
    <p>There must be at least two players added to
       the event before the match can start.<p>
  <% elsif !@event.rounds.empty?%>  
<p>Check a box to declare a winner. Check both boxes or
   leave both blank to declare a tie.<p>
      <%= f.fields_for :rounds do |round_form| %>
	<%= round_form.hidden_field :active, :value => false%>
	<div class="<%=round_form.object.get_style()%>">
          <%round_form.object.games.order("id")%>
	  <%= round_form.fields_for :games do |game_form| %>
	    <div class="bracket">
	      <%game_form.object.contestants.each do |p|%>
                <div class="<%=game_form.object.get_2p_styling(p)%>">
		  <span><%=p.name%></span>
	          <div class="checkbox">
                  <%if p == game_form.object.contestants.first%>
                    <%= game_form.check_box :p1_win%>
                  <%else%>
                    <%= game_form.check_box :p2_win%>
                  <%end%>
	        </div>
                </div>
            <% end %>
            </div>
	  <% end %>
        </div>
      <% end %>
  <%else%>
    <p>Press 'New Round' to generate a new round<p>
  <% end %>

</div>

<%if !@event.rounds.empty?%>
<div>
  <table>
    <tr>
      <th>Player</th>
      <th>Losses</th>
      <th>Wins</th>
      <th>Ties</th>
    </tr>
    <%@event.scores.each do |p,s_arr|%>
      <tr>
	<td><%=p.name%></td>
	<td><%=s_arr[0]%></td>
	<td><%=s_arr[1]%></td>
	<td><%=s_arr[2]%></td>
      </tr>
    <%end%>
  </table>
</div>
<%end%>

<div class="menu">
  <div class="title"> Menu </div>
<% if @new_round_disabled %>
  <a class="tab">
    <img src="<%= image_path('pen.svg') %>"/>
    <span><strike>New Round</strike></span>
  </a>
<%else%>
  <a class="result tab">
 <img src="<%= image_path('pen.svg') %>"/>
  <% if @event.rounds.empty? %>
    <span> Start Match </span>
  <%else%>
    <span> Advance Match </span>
  <%end%>
</a>
<a class="tab" href=<%=undo_round_path%> data-method="delete"> 
  <img src="<%= image_path('trophy.svg') %>"/>
  <span> Undo Round </span>
</a>
<%end%>
  <a class="tab" href="/mockup-event-info">
    <img src="<%= image_path('pen.svg') %>"/>
    <span> Edit Info </span>
  </a>
  <a class="tab" href="/mockup-event-checkin"> 
    <img src="<%= image_path('person.svg') %>"/>
    <span> Check In </span>
  </a>
  <!--<a class="tab" href="#"> 
    <img src="<%= image_path('money.svg') %>"/>
    <span> Rewards </span>
  </a>-->
  <a class="tab" href="/mockup-event-summary">
    <img src="<%= image_path('stats.svg') %>"/>
    <span> Summary </span>
  </a>
  <a class="tab" href="/mockup-events"> 
    <img src="<%= image_path('trash.svg') %>"/>
    <span> Delete </span>
  </a>
</div>
<%end%>

app/views/events/show-brackets.html.erb
<script>
$(function() {
  $( "#dialog" ).dialog({
    autoOpen: false,
  });

  $( ".result" ).click(function() {
    $( "#dialog" ).dialog( "open" );
  });
});
</script>
<div id="dialog" title="Match Result">
  <p>Who won the match?</p>
  <button class="left-button"> Player 1 </button>
  <button class="center-button"> Player 2 </button>
  <button class="right-button"> Tie </button>
</div>

<h1 class="notification"><%=@event.name%><span class="orange"> Brackets </span></h1>

<div class="event-management">
  <% if @new_round %>  
    <p><%=@new_round.games.count%><p>
    <%= form_for @event, url: { :action => :update } do |f| %>
      <%= f.text_field :name %>
      <%= f.fields_for :rounds do |round| %>
        <%= round.number_field :round_number %>
        <%= round.fields_for :games do |game_form| %>
            <%= game_form.radio_button :p1_win, true%>
        <% end %>
      <% end %>
      <%= f.submit %>
    <% end %>
  <%else%>
    <p>HELLOOOOO<p>
  <% end %>

</div>

<div class="menu">
  <%= link_to "New Round", new_round_path, :class => 'tab'%>
</div>

<div class="menu">
  <div class="title"> Menu </div>
  <a class="tab" href="/mockup-event-info">
    <img src="<%= image_path('pen.svg') %>"/>
    <span> Edit Info </span>
  </a>
  <a class="tab" href="/mockup-event-checkin"> 
    <img src="<%= image_path('person.svg') %>"/>
    <span> Check In </span>
  </a>
  <a class="tab" href="/mockup-event-brackets"> 
    <img src="<%= image_path('trophy.svg') %>"/>
    <span> Brackets </span>
  </a>
  <!--<a class="tab" href="#"> 
    <img src="<%= image_path('money.svg') %>"/>
    <span> Rewards </span>
  </a>-->
  <a class="tab" href="/mockup-event-summary">
    <img src="<%= image_path('stats.svg') %>"/>
    <span> Summary </span>
  </a>
  <a class="tab" href="/mockup-events"> 
    <img src="<%= image_path('trash.svg') %>"/>
    <span> Delete </span>
  </a>
</div>

app/views/events/show.html.erb
<h1 class="notification"> <%=@event.name %> <span class="orange"> Information </span></h1>
<div class="event-management">
  <table>
    <tr>
      <th>Type</th>
      <th>Value</th>
    </tr>
    <tr>
      <td style="width: 150px;">Name</td>
      <td><%=@event.name %></td>
    </tr>
    <tr>
      <td style="width: 150px;">Date</td>
      <td><%=@event.date %></td>
    </tr>
    <tr>
      <td style="width: 150px;">Event Type</td>
      <td><%=@event.event_type %></td>
    </tr>
    <tr>
      <td style="width: 150px;">Bracket</td>
      <td><%=@event.bracket %></td>
    </tr>
    <tr style="height: 150px">
      <td style="width: 150px;">Description</td>
      <td><textarea type="text"><%=@event.description %></textarea></td>
    </tr>
  </table>
  <a href=<%=edit_event_path(@event)%>><button class="submit">Edit</button></a>
</div>
<div class="menu">
  <div class="title"> Menu </div>
  <a class="tab" href=<%=event_path(@event)%>>
    <img src="<%= image_path('pen.svg') %>"/>
    <span> Information </span>
  </a>
  <a class="tab" href="#"> 
    <img src="<%= image_path('person.svg') %>"/>
    <span> Check In </span>
  </a>
  <a class="tab" href=<%=bracket_path%>> 
    <img src="<%= image_path('trophy.svg') %>"/>
    <span> Brackets </span>
  </a>
  <!--<a class="tab" href="#"> 
    <img src="<%= image_path('money.svg') %>"/>
    <span> Rewards </span>
  </a>-->
  <a class="tab" href="#">
    <img src="<%= image_path('stats.svg') %>"/>
    <span> Summary </span>
  </a>
  <a class="tab" href=<%=event_path(@event)%> data-confirm="Are you sure you want to delete this event?" data-method="delete"> 
    <img src="<%= image_path('trash.svg') %>"/>
    <span> Delete </span>
  </a>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>