config/routes.rb
Rails.application.routes.draw do

  resources 'events'
  resources :users
  resources 'games'
  get 'events/:id/bracket' => 'events#show_bracket', as: :bracket
  get 'events/:id/new_round' => 'events#new_round', as: :new_round
  patch 'events/:id/bracket' =>  'events#update_bracket', as: :update_bracket
  delete 'events/:id/undo_round' => 'events#undo_round', as: :undo_round
  patch 'events/:id/save_event' => 'events#save_event', as: :save_event
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new',  via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'get', via: 'delete'

  get 'template/index', :path => 'template'
  get 'template/new'
  get 'template/show'
  get 'template/edit'

  get 'mockup/index', :path => 'mockup-login'
  get 'mockup/new', :path => 'mockup-new-event'
  get 'mockup/events', :path => 'mockup-events'
  get 'mockup/info', :path => 'mockup-event-info'
  get 'mockup/checkin', :path => 'mockup-event-checkin'
  get 'mockup/brackets', :path => 'mockup-event-brackets'
  get 'mockup/summary', :path => 'mockup-event-summary'

  root 'sessions#new'#'mockup#index' 

end

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Outgame</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/png" href="<%= image_path('favicon.png') %>"/>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800' rel='stylesheet' type='text/css'>
</head>
<body>
<nav>
  <a class="tab" href="/mockup-new-event"><img src="<%= image_path('add.svg') %>"/></a>
  <div class="divider"></div>
  <a class="tab" href="/mockup-events"><img src="<%= image_path('list.svg') %>"/></a>
  <div class="divider"></div>
  <span> Welcome, <a class="link" href="/mockup-login"> Games of Berkeley </a></span>
</nav>
<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Outgame</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="icon" type="image/png" href="<%= image_path('favicon.png') %>"/>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800' rel='stylesheet' type='text/css'>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
  </head>
  <body>
    <nav>
      <%= link_to(image_tag('exit.svg'), signout_path, class: 'tab', method: 'delete')%>
      <div class="divider"></div>
      <a class="tab" href=<%= new_event_path%>><img src="<%= image_path('add.svg') %>"/></a>
      <div class="divider"></div>
      <a class="tab" href=<%= events_path%>><img src="<%= image_path('list.svg') %>"/></a>
      <div class="divider"></div>
      <% if current_user %>
        <span> Welcome, <a class="link" href="<%= events_path%>"> <%= current_user.name %> </a></span>
      <% end %>
    </nav>
    <% if flash[:success] or flash[:error]%>
      <div class="action-notification">
        <img src="/assets/notification.svg">
        <span><%= flash[:success] %></span>
        <span><%= flash[:error] %></span>
      </div>
      <div class="action-notification-spacer"></div>
      <% flash.clear %>
    <% end %>
    <%= yield %>
  </body>
</html>